# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1588302716);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1588305373);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1588341253);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1588300444);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1588354990);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1588305493);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1588031874);
user_pref("browser.laterrun.bookkeeping.sessionCount", 9);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 42);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1588354962604");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1588358562604");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180315145708");
user_pref("browser.slowStartup.averageTime", 1918);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20180315145708");
user_pref("browser.startup.homepage_override.mstone", "52.7.0");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 1);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20200430);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1588031936344");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.firstPaint", 2153);
user_pref("datareporting.sessions.current.main", 320);
user_pref("datareporting.sessions.current.sessionRestored", 2257);
user_pref("datareporting.sessions.current.startTime", "1588354958473");
user_pref("datareporting.sessions.current.totalTime", 29);
user_pref("datareporting.sessions.currentIndex", 8);
user_pref("datareporting.sessions.previous.0", "{\"s\":1588031872276,\"a\":8,\"t\":83861,\"c\":true,\"m\":480,\"fp\":4237,\"sr\":4047}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1588203332930,\"a\":19,\"t\":9647,\"c\":true,\"m\":850,\"fp\":4782,\"sr\":4684}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1588286521776,\"a\":10,\"t\":65,\"c\":true,\"m\":540,\"fp\":3245,\"sr\":3341}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1588286611342,\"a\":1,\"t\":13,\"c\":true,\"m\":131,\"fp\":2139,\"sr\":2190}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1588300292745,\"a\":1,\"t\":53,\"c\":false,\"m\":325,\"fp\":2531,\"sr\":2633}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1588302684578,\"a\":2,\"t\":23,\"c\":false,\"m\":300,\"fp\":1548,\"sr\":2474}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1588305221594,\"a\":14,\"t\":34077,\"c\":true,\"m\":330,\"fp\":2146,\"sr\":2657}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1588339702601,\"a\":3,\"t\":2437,\"c\":true,\"m\":190,\"fp\":1768,\"sr\":1857}");
user_pref("e10s.rollout.cohort", "test");
user_pref("e10s.rollout.cohortSample", "0.827030");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.bootstrappedAddons", "{\"aushelper@mozilla.org\":{\"version\":\"2.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"e10srollout@mozilla.org\":{\"version\":\"1.10\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"firefox@getpocket.com\":{\"version\":\"1.0.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false}}");
user_pref("extensions.databaseSchema", 19);
user_pref("extensions.e10s.rollout.blocklist", "{dc572301-7619-498c-a57d-39143191b318};support@lastpass.com;");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "51set1");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.7.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "52.7.0");
user_pref("extensions.lastPlatformVersion", "52.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"aushelper@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi\",\"e\":true,\"v\":\"2.0\",\"st\":1521126626000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.10\",\"st\":1521126626000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.5\",\"st\":1521126627000},\"webcompat@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1521126627000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.7.0\",\"st\":1521126626000}}}");
user_pref("idle.lastDailyNotification", 1588300516);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1588031937);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20180315145708");
user_pref("media.gmp-manager.lastCheck", 1588300355);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1588032115);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1588305373);
user_pref("services.blocklist.clock_skew_seconds", -1);
user_pref("services.blocklist.gfx.checked", 1588305373);
user_pref("services.blocklist.last_update_seconds", 1588305373);
user_pref("services.blocklist.plugins.checked", 1588305373);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1588032115);
user_pref("toolkit.startup.last_success", 1588354958);
user_pref("toolkit.telemetry.cachedClientID", "2b126904-42f1-49bd-b57e-51bd3312de55");
user_pref("toolkit.telemetry.previousBuildID", "20180315145708");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
